### ISSUE TITLE
Search API Issue

### ISSUE THREAD

**Issue by NilusCodeRepo** [ONDC-Official/ONDC-FIS-Specifications#227]
@92shreyansh
https://staging.gateway.proteantech.in/search

I'm subscribed as Buyer and integrating Health Insurance.

Below is the hosted on_search implementaion 
// Route for handling on_search requests
app.post('/onboarding/on_search', function (req, res) {
    let search_req = req.body;
    const resp = {answer: search_req};
   res.status(200).json(resp); 

});

When i call the search mock API, It is returning acknowledgemnt message but not getting static catelogues. I also checked by changing city code to 'std:080' but didn't work.
Please look into this.
Payload: 
{
    "context": {
        "action": "search",
        "bap_id": "www.policyboss.com/ondc",
        "bap_uri": "https://www.policyboss.com/ondc/onboarding",
        "domain": "ONDC:FIS13",
        "location": {
            "country": {
                "code": "IND"
            },
            "city": {
                "code": "*"
            }
        },
        "message_id": "70e78966-57a0-455f-86a4-cfa70d5a63aa",
        "timestamp": "2024-03-26T13:40:31.700Z",
        "transaction_id": "ecc9ccf3-b539-4d53-bcbc-1fa2bd67d458",
        "ttl": "PT24H",
        "version": "2.0.0"
    },
    "message": {
        "intent": {
            "category": {
                "descriptor": {
                    "code": "HEALTH_INSURANCE"
                }
            },
            "payment": {
                "collected_by": "BPP",
                "tags": [
                    {
                        "descriptor": {
                            "code": "BUYER_FINDER_FEES"
                        },
                        "display": false,
                        "list": [
                            {
                                "descriptor": {
                                    "code": "BUYER_FINDER_FEES_TYPE"
                                },
                                "value": "percent-annualized"
                            },
                            {
                                "descriptor": {
                                    "code": "BUYER_FINDER_FEES_PERCENTAGE"
                                },
                                "value": "1"
                            }
                        ]
                    },
                    {
                        "descriptor": {
                            "code": "SETTLEMENT_TERMS"
                        },
                        "display": false,
                        "list": [
                            {
                                "descriptor": {
                                    "code": "SETTLEMENT_WINDOW"
                                },
                                "value": "PT60M"
                            },
                            {
                                "descriptor": {
                                    "code": "SETTLEMENT_BASIS"
                                },
                                "value": "Delivery"
                            },
                            {
                                "descriptor": {
                                    "code": "DELAY_INTEREST"
                                },
                                "value": "2.5"
                            },
                            {
                                "descriptor": {
                                    "code": "STATIC_TERMS"
                                },
                                "value": "https://bap.credit.becknprotocol.io/personal-banking/loans/personal-loan"
                            }
                        ]
                    }
                ]
            }
        }
    }
}

Response:
{
    "context": {
        "domain": "ONDC:FIS13",
        "location": {
            "city": {
                "code": "*"
            },
            "country": {
                "code": "IND"
            }
        },
        "action": "search",
        "version": "2.0.0",
        "bap_id": "www.policyboss.com/ondc",
        "bap_uri": "https://www.policyboss.com/ondc/onboarding",
        "transaction_id": "ecc9ccf3-b539-4d53-bcbc-1fa2bd67d458",
        "message_id": "70e78966-57a0-455f-86a4-cfa70d5a63aa",
        "timestamp": "2024-03-26T10:31:20.152Z",
        "ttl": "PT24H"
    },
    "message": {
        "ack": {
            "status": "ACK"
        }
    }
}

**Comment by madhus1025** [comment]
Any update on this ?
