### ISSUE TITLE
ONDC FIS14 > Sample request payloads & attributes yaml files mismatch or incorrect

### ISSUE THREAD

**Issue by ravindra-aditya** [ONDC-Official/ONDC-FIS-Specifications#340]
Hi Team,

I'm wondering do we really need to follow the attributes yaml files since they are being outdated or mismatch with sample request payloads placed in the examples.

Need clarification is that attributes specifications we should follow then some of the attributes are still laying as optional for example: "_description". example [here](https://github.com/ONDC-Official/ONDC-FIS-Specifications/blob/draft-FIS14-enhancements/api/components/attributes/mutual-funds/index.yaml)

Suggest us which one to follow, preferably both attributes and samples should go hand in hand.

**Comment by ravindra-aditya** [comment]
@anuj-ondc Please review and help us on this topic at earliest with your comments.

**Comment by ravindra-aditya** [comment]
@anuj-ondc @sandeepshahi Please help.

**Comment by anuj-ondc** [comment]
@ravindra-aditya, For any references related to protocol please follow the developer guide only: https://ondc-official.github.io/ONDC-FIS-Specifications
